worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;

    server {
        # Escuchar en puerto 8080 para desarrollo
        listen 8080;
        server_name localhost;

        # Health check: /health devuelve 200 {"status":"ok"}
        location /health {
            return 200 '{"status":"ok"}';
            add_header Content-Type application/json;
        }

        # Enrutar a Auth Service corriendo en la PC (host)
        location /api/v1/auth {
            proxy_pass http://host.docker.internal:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Enrutar a Clients Service corriendo en la PC (host)
        location /api/v1/clients {
            proxy_pass http://host.docker.internal:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Enrutar a Merchants Service corriendo en la PC (host)
        location /api/v1/merchants {
            proxy_pass http://host.docker.internal:8003;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Enrutar a Payments Service corriendo en la PC (host) - Pagos
        location /api/v1/payments {
            proxy_pass http://host.docker.internal:8004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Enrutar a Payments Service corriendo en la PC (host) - Tarjetas
        location /api/v1/cards {
            proxy_pass http://host.docker.internal:8004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
